// Genererad från match-data.js, "Segeltorp P15 .xlsx" och "p14.xlsx".
window.MATCH_SCHEDULE = {
  "players": [
    "Adrian",
    "Alexander HB",
    "Alexander L",
    "Alfred",
    "Alvin",
    "Axel",
    "Collin",
    "Dante",
    "Edward",
    "Elias",
    "Elliot Ö",
    "Elliott S",
    "Elton",
    "Hugo",
    "Innes",
    "Ivo",
    "Kristofer",
    "Leo B",
    "Leo M",
    "Leon",
    "Lorenz",
    "Loui",
    "Love",
    "Olof",
    "Victor",
    "Vidar",
    "Walter",
    "Wilhelm"
  ],
  "matches": [
    {
      "matchNumber": "150343002",
      "series": "B Södra",
      "category": "P15",
      "home": "Tyresö Trollbäcken IBK (B)",
      "away": "Segeltorps IF IBF (B)",
      "opponent": "Tyresö Trollbäcken IBK (B)",
      "date": "2026-09-26T12:00",
      "timeTbd": false,
      "venue": "Strandhallen - Tyresö",
      "round": 1,
      "assignedPlayers": [
        "Adrian",
        "Axel",
        "Edward",
        "Innes",
        "Ivo",
        "Leo M",
        "Lorenz",
        "Love",
        "Olof",
        "Wilhelm"
      ],
      "assignedCoaches": [
        "Calle",
        "Kian",
        "Johan"
      ]
    },
    {
      "matchNumber": "150326002",
      "series": "P14 B",
      "category": "P14",
      "home": "Segeltorps IF IBF",
      "away": "Sköndals IK",
      "opponent": "Sköndals IK",
      "date": "2026-09-27T12:00",
      "timeTbd": false,
      "venue": "Utsäljehallen",
      "round": 1,
      "assignedPlayers": [
        "Alfred",
        "Elliot Ö",
        "Kristofer"
      ],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150317003",
      "series": "A Södra",
      "category": "P15",
      "home": "Segeltorps IF IBF",
      "away": "Huddinge IBS (A)",
      "opponent": "Huddinge IBS (A)",
      "date": "2026-09-27T16:30",
      "timeTbd": false,
      "venue": "Tomtbergahallen",
      "round": 1,
      "assignedPlayers": [
        "Alvin",
        "Elliott S",
        "Elliot Ö",
        "Elton",
        "Leo B",
        "Leo M",
        "Loui",
        "Walter",
        "Wilhelm"
      ],
      "assignedCoaches": [
        "Ellenor",
        "Robin",
        "Oskar"
      ]
    },
    {
      "matchNumber": "150317009",
      "series": "A Södra",
      "category": "P15",
      "home": "Älvsjö AIK IBF",
      "away": "Segeltorps IF IBF",
      "opponent": "Älvsjö AIK IBF",
      "date": "2026-10-03T11:30",
      "timeTbd": false,
      "venue": "Kämpetorpshallen 1",
      "round": 2,
      "assignedPlayers": [
        "Alexander HB",
        "Alfred",
        "Alvin",
        "Elton",
        "Innes",
        "Ivo",
        "Kristofer",
        "Leo B",
        "Leon",
        "Wilhelm"
      ],
      "assignedCoaches": [
        "Cindi",
        "Robin",
        "Johan"
      ]
    },
    {
      "matchNumber": "150326010",
      "series": "P14 B",
      "category": "P14",
      "home": "Ingarö IF",
      "away": "Segeltorps IF IBF",
      "opponent": "Ingarö IF",
      "date": "2026-10-03T13:15",
      "timeTbd": false,
      "venue": "Ingarö Sporthall",
      "round": 2,
      "assignedPlayers": [
        "Elliott S",
        "Hugo",
        "Leo M"
      ],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150344008",
      "series": "B Östra",
      "category": "P15",
      "home": "Nacka IBK (B)",
      "away": "Segeltorps IF IBF (A)",
      "opponent": "Nacka IBK (B)",
      "date": "2026-10-04T11:30",
      "timeTbd": false,
      "venue": "Ormingehallen",
      "round": 2,
      "assignedPlayers": [
        "Collin",
        "Edward",
        "Elias",
        "Elliott S",
        "Elliot Ö",
        "Hugo",
        "Lorenz",
        "Loui",
        "Love",
        "Walter"
      ],
      "assignedCoaches": [
        "Calle",
        "Ellenor"
      ]
    },
    {
      "matchNumber": "150343011",
      "series": "B Södra",
      "category": "P15",
      "home": "Värmdö IF (B)",
      "away": "Segeltorps IF IBF (B)",
      "opponent": "Värmdö IF (B)",
      "date": "2026-10-10T11:00",
      "timeTbd": false,
      "venue": "Värmdö sporthall",
      "round": 3,
      "assignedPlayers": [
        "Alexander HB",
        "Axel",
        "Elias",
        "Elliot Ö",
        "Kristofer",
        "Leon",
        "Love",
        "Olof",
        "Vidar",
        "Wilhelm"
      ],
      "assignedCoaches": [
        "Calle",
        "Linus"
      ]
    },
    {
      "matchNumber": "150317015",
      "series": "A Södra",
      "category": "P15",
      "home": "Segeltorps IF IBF",
      "away": "Värmdö IF",
      "opponent": "Värmdö IF",
      "date": "2026-10-11T09:30",
      "timeTbd": false,
      "venue": "Utsäljehallen",
      "round": 3,
      "assignedPlayers": [
        "Adrian",
        "Alexander HB",
        "Alfred",
        "Alvin",
        "Elliott S",
        "Hugo",
        "Leo B",
        "Leo M",
        "Loui",
        "Walter"
      ],
      "assignedCoaches": [
        "Cindi",
        "Ellenor"
      ]
    },
    {
      "matchNumber": "150344014",
      "series": "B Östra",
      "category": "P15",
      "home": "Segeltorps IF IBF (A)",
      "away": "Värmdö IF (A)",
      "opponent": "Värmdö IF (A)",
      "date": "2026-10-11T10:30",
      "timeTbd": false,
      "venue": "Utsäljehallen",
      "round": 3,
      "assignedPlayers": [
        "Axel",
        "Collin",
        "Edward",
        "Elias",
        "Elton",
        "Innes",
        "Ivo",
        "Leon",
        "Lorenz",
        "Vidar"
      ],
      "assignedCoaches": [
        "Robin",
        "Johan"
      ]
    },
    {
      "matchNumber": "150326014",
      "series": "P14 B",
      "category": "P14",
      "home": "Segeltorps IF IBF",
      "away": "Nacka IBK",
      "opponent": "Nacka IBK",
      "date": "2026-10-11T11:45",
      "timeTbd": false,
      "venue": "Utsäljehallen",
      "round": 3,
      "assignedPlayers": [
        "Alexander HB",
        "Kristofer",
        "Wilhelm"
      ],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150344020",
      "series": "B Östra",
      "category": "P15",
      "home": "Nacka IBK (A)",
      "away": "Segeltorps IF IBF (A)",
      "opponent": "Nacka IBK (A)",
      "date": "2026-10-17T14:00",
      "timeTbd": false,
      "venue": "Myrsjöskolan",
      "round": 4,
      "assignedPlayers": [
        "Adrian",
        "Alvin",
        "Axel",
        "Collin",
        "Edward",
        "Leo M",
        "Lorenz",
        "Olof",
        "Walter",
        "Vidar"
      ],
      "assignedCoaches": [
        "Ellenor",
        "Robin"
      ]
    },
    {
      "matchNumber": "150326021",
      "series": "P14 B",
      "category": "P14",
      "home": "Huddinge IBS (B)",
      "away": "Segeltorps IF IBF",
      "opponent": "Huddinge IBS (B)",
      "date": "2026-10-18T10:00",
      "timeTbd": false,
      "venue": "Glömstahallen",
      "round": 4,
      "assignedPlayers": [
        "Alexander HB",
        "Alvin",
        "Walter"
      ],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150317021",
      "series": "A Södra",
      "category": "P15",
      "home": "FBI Tullinge",
      "away": "Segeltorps IF IBF",
      "opponent": "FBI Tullinge",
      "date": "2026-10-18T15:10",
      "timeTbd": false,
      "venue": "Trädgårdsstadshallen (Tullinge)",
      "round": 4,
      "assignedPlayers": [
        "Alfred",
        "Elliot Ö",
        "Elton",
        "Hugo",
        "Innes",
        "Ivo",
        "Kristofer",
        "Leo B",
        "Love",
        "Wilhelm"
      ],
      "assignedCoaches": [
        "Cindi"
      ]
    },
    {
      "matchNumber": "150326032",
      "series": "P14 B",
      "category": "P14",
      "home": "Älta IF",
      "away": "Segeltorps IF IBF",
      "opponent": "Älta IF",
      "date": "2026-10-19T00:00",
      "timeTbd": true,
      "venue": "Stavsborgs sporthall",
      "round": 6,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150344002",
      "series": "B Östra",
      "category": "P15",
      "home": "Segeltorps IF IBF (A)",
      "away": "Tyresö Trollbäcken IBK (A)",
      "opponent": "Tyresö Trollbäcken IBK (A)",
      "date": "2026-11-01T15:00",
      "timeTbd": false,
      "venue": "Utsäljehallen",
      "round": 1,
      "assignedPlayers": [
        "Alfred",
        "Collin",
        "Elias",
        "Elliott S",
        "Hugo",
        "Kristofer",
        "Leon",
        "Loui",
        "Olof"
      ],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150344025",
      "series": "B Östra",
      "category": "P15",
      "home": "Nynäshamns IBK (B)",
      "away": "Segeltorps IF IBF (A)",
      "opponent": "Nynäshamns IBK (B)",
      "date": "2026-11-07T11:00",
      "timeTbd": false,
      "venue": "Kvarnängshallen",
      "round": 5,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150343023",
      "series": "B Södra",
      "category": "P15",
      "home": "Segeltorps IF IBF (B)",
      "away": "Salems IF",
      "opponent": "Salems IF",
      "date": "2026-11-08T09:15",
      "timeTbd": false,
      "venue": "Utsäljehallen",
      "round": 5,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150326038",
      "series": "P14 B",
      "category": "P14",
      "home": "Segeltorps IF IBF",
      "away": "FBI Tullinge",
      "opponent": "FBI Tullinge",
      "date": "2026-11-08T11:45",
      "timeTbd": false,
      "venue": "Utsäljehallen",
      "round": 7,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150317032",
      "series": "A Södra",
      "category": "P15",
      "home": "Ingarö IF",
      "away": "Segeltorps IF IBF",
      "opponent": "Ingarö IF",
      "date": "2026-11-14T14:45",
      "timeTbd": false,
      "venue": "Ingarö Sporthall",
      "round": 6,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150343029",
      "series": "B Södra",
      "category": "P15",
      "home": "Segeltorps IF IBF (B)",
      "away": "Nacka IBK (C)",
      "opponent": "Nacka IBK (C)",
      "date": "2026-11-15T11:00",
      "timeTbd": false,
      "venue": "Tomtbergahallen",
      "round": 6,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150326043",
      "series": "P14 B",
      "category": "P14",
      "home": "Tyresö Trollbäcken IBK",
      "away": "Segeltorps IF IBF",
      "opponent": "Tyresö Trollbäcken IBK",
      "date": "2026-11-15T11:30",
      "timeTbd": false,
      "venue": "Strandhallen - Tyresö",
      "round": 8,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150344034",
      "series": "B Östra",
      "category": "P15",
      "home": "Ingarö IF",
      "away": "Segeltorps IF IBF (A)",
      "opponent": "Ingarö IF",
      "date": "2026-11-21T10:00",
      "timeTbd": false,
      "venue": "Ingarö Sporthall",
      "round": 7,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150317037",
      "series": "A Södra",
      "category": "P15",
      "home": "Nacka IBK",
      "away": "Segeltorps IF IBF",
      "opponent": "Nacka IBK",
      "date": "2026-11-22T10:00",
      "timeTbd": false,
      "venue": "Ormingehallen",
      "round": 7,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150326050",
      "series": "P14 B",
      "category": "P14",
      "home": "Segeltorps IF IBF",
      "away": "Skogås/Trångsunds IBK",
      "opponent": "Skogås/Trångsunds IBK",
      "date": "2026-11-22T12:00",
      "timeTbd": false,
      "venue": "Utsäljehallen",
      "round": 9,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150343035",
      "series": "B Södra",
      "category": "P15",
      "home": "Segeltorps IF IBF (B)",
      "away": "Farsta IBK",
      "opponent": "Farsta IBK",
      "date": "2026-11-22T12:15",
      "timeTbd": false,
      "venue": "Tomtbergahallen",
      "round": 7,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150343040",
      "series": "B Södra",
      "category": "P15",
      "home": "Sköndals IK",
      "away": "Segeltorps IF IBF (B)",
      "opponent": "Sköndals IK",
      "date": "2026-11-28T14:00",
      "timeTbd": false,
      "venue": "Bandhagshallen",
      "round": 8,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150326060",
      "series": "P14 B",
      "category": "P14",
      "home": "Salems IF",
      "away": "Segeltorps IF IBF",
      "opponent": "Salems IF",
      "date": "2026-11-29T13:30",
      "timeTbd": false,
      "venue": "Skogsängshallen",
      "round": 10,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150317045",
      "series": "A Södra",
      "category": "P15",
      "home": "Segeltorps IF IBF",
      "away": "Farsta IBK",
      "opponent": "Farsta IBK",
      "date": "2026-11-29T14:00",
      "timeTbd": false,
      "venue": "Utsäljehallen",
      "round": 8,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150344038",
      "series": "B Östra",
      "category": "P15",
      "home": "Segeltorps IF IBF (A)",
      "away": "Älvsjö AIK IBF (A)",
      "opponent": "Älvsjö AIK IBF (A)",
      "date": "2026-11-29T15:00",
      "timeTbd": false,
      "venue": "Utsäljehallen",
      "round": 8,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150343045",
      "series": "B Södra",
      "category": "P15",
      "home": "Segeltorps IF IBF (B)",
      "away": "Tumba GOIF",
      "opponent": "Tumba GOIF",
      "date": "2026-12-05T15:00",
      "timeTbd": false,
      "venue": "Tomtbergahallen",
      "round": 9,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150317049",
      "series": "A Södra",
      "category": "P15",
      "home": "Segeltorps IF IBF",
      "away": "Hammarby IF IBF",
      "opponent": "Hammarby IF IBF",
      "date": "2026-12-05T18:00",
      "timeTbd": false,
      "venue": "Tomtbergahallen",
      "round": 9,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150326026",
      "series": "P14 B",
      "category": "P14",
      "home": "Segeltorps IF IBF",
      "away": "IFK Haninge",
      "opponent": "IFK Haninge",
      "date": "2026-12-06T10:45",
      "timeTbd": false,
      "venue": "Glömstahallen",
      "round": 5,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150344042",
      "series": "B Östra",
      "category": "P15",
      "home": "Älta IF",
      "away": "Segeltorps IF IBF (A)",
      "opponent": "Älta IF",
      "date": "2026-12-06T14:00",
      "timeTbd": false,
      "venue": "Stavsborgs sporthall",
      "round": 9,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150326071",
      "series": "P14 B",
      "category": "P14",
      "home": "Sköndals IK",
      "away": "Segeltorps IF IBF",
      "opponent": "Sköndals IK",
      "date": "2026-12-12T14:00",
      "timeTbd": false,
      "venue": "Sköndalshallen",
      "round": 12,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150344046",
      "series": "B Östra",
      "category": "P15",
      "home": "Segeltorps IF IBF (A)",
      "away": "FBI Tullinge (B)",
      "opponent": "FBI Tullinge (B)",
      "date": "2026-12-13T10:00",
      "timeTbd": false,
      "venue": "Tomtbergahallen",
      "round": 10,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150317056",
      "series": "A Södra",
      "category": "P15",
      "home": "Älta IF",
      "away": "Segeltorps IF IBF",
      "opponent": "Älta IF",
      "date": "2026-12-13T14:15",
      "timeTbd": false,
      "venue": "Stavsborgs sporthall",
      "round": 10,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150326074",
      "series": "P14 B",
      "category": "P14",
      "home": "Segeltorps IF IBF",
      "away": "Ingarö IF",
      "opponent": "Ingarö IF",
      "date": "2026-12-20T11:45",
      "timeTbd": false,
      "venue": "Utsäljehallen",
      "round": 13,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150326082",
      "series": "P14 B",
      "category": "P14",
      "home": "Nacka IBK",
      "away": "Segeltorps IF IBF",
      "opponent": "Nacka IBK",
      "date": "2027-01-10T18:30",
      "timeTbd": false,
      "venue": "Ormingehallen",
      "round": 14,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150326086",
      "series": "P14 B",
      "category": "P14",
      "home": "Segeltorps IF IBF",
      "away": "Huddinge IBS (B)",
      "opponent": "Huddinge IBS (B)",
      "date": "2027-01-16T10:15",
      "timeTbd": false,
      "venue": "Glömstahallen",
      "round": 15,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150326093",
      "series": "P14 B",
      "category": "P14",
      "home": "IFK Haninge",
      "away": "Segeltorps IF IBF",
      "opponent": "IFK Haninge",
      "date": "2027-01-24T12:30",
      "timeTbd": false,
      "venue": "Lyckeby Sporthall",
      "round": 16,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150326098",
      "series": "P14 B",
      "category": "P14",
      "home": "Segeltorps IF IBF",
      "away": "Älta IF",
      "opponent": "Älta IF",
      "date": "2027-01-31T13:15",
      "timeTbd": false,
      "venue": "Utsäljehallen",
      "round": 17,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150326104",
      "series": "P14 B",
      "category": "P14",
      "home": "FBI Tullinge",
      "away": "Segeltorps IF IBF",
      "opponent": "FBI Tullinge",
      "date": "2027-02-06T19:00",
      "timeTbd": false,
      "venue": "Tullingehallen",
      "round": 18,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150326110",
      "series": "P14 B",
      "category": "P14",
      "home": "Segeltorps IF IBF",
      "away": "Tyresö Trollbäcken IBK",
      "opponent": "Tyresö Trollbäcken IBK",
      "date": "2027-02-14T13:15",
      "timeTbd": false,
      "venue": "Utsäljehallen",
      "round": 19,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150326115",
      "series": "P14 B",
      "category": "P14",
      "home": "Skogås/Trångsunds IBK",
      "away": "Segeltorps IF IBF",
      "opponent": "Skogås/Trångsunds IBK",
      "date": "2027-02-20T12:45",
      "timeTbd": false,
      "venue": "Skogåshallen",
      "round": 20,
      "assignedPlayers": [],
      "assignedCoaches": []
    },
    {
      "matchNumber": "150326122",
      "series": "P14 B",
      "category": "P14",
      "home": "Segeltorps IF IBF",
      "away": "Salems IF",
      "opponent": "Salems IF",
      "date": "2027-03-14T14:30",
      "timeTbd": false,
      "venue": "Utsäljehallen",
      "round": 21,
      "assignedPlayers": [],
      "assignedCoaches": []
    }
  ],
  "coaches": [
    "Calle",
    "Cindi",
    "Ellenor",
    "Robin",
    "Oskar",
    "Kian",
    "Johan",
    "Linus",
    "Magnus"
  ]
};
